### PR TITLE
Use single shared method for return code checking.

### LINKED ISSUE #49: Proper use of Libsodium return codes
Libsodium seems to have a consistent strategy [documented](https://doc.libsodium.org/quickstart#how-do-i-check-if-a-function-call-succeeded) for its return codes. However, I am seeing multiple different strategies for handling the returns from api calls in the library: [[1]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/commonMain/kotlin/com.ionspin.kotlin.crypto/GeneralLibsodiumException.kt) [[2]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/secretbox/SecretBox.kt#L32-L34) [[3]](https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/0.9.2/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/signature/SignatureJvm.kt#L42-L44).

Is there a rationale for this? or is there need for some clean up here?

My concern is primarily with the strategy of checking for an error code, such as in this method:
```kotlin
fun Int.ensureLibsodiumSuccess() {
  if (this == -1) {
    throw GeneralLibsodiumException()
  }
}
```
This seems like it should be **inverted** to check for a successful code rather than the error code, or it could inadvertently return successful if an unknown error code is returned.

### PR DESCRIPTION
**Pull request by ReneeVandervelde**
This defers the return code logic to a named method `isLibsodiumSuccessCode` to reduce the likelihood of error when checking codes. This will also now throw an `IllegalStateException` in the event that an unknown code is returned.

---------

**Please double-check the comparisons here** to make sure nothing was inadvertently changed -- these code checks are quite important.

Closes #49

### CODE REVIEW

File: multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/util/LibsodiumUtil.kt [hunk 1]
```diff
@@ -30,7 +30,7 @@ actual object LibsodiumUtil {
         val result = sodium_memcmp(firstPinned.toPtr(), secondPinned.toPtr(), first.size.convert())
         firstPinned.unpin()
         secondPinned.unpin()
-        return result == 0
+        return result.isLibSodiumSuccessCode()
```
Comment (ionspin) [inline multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/util/LibsodiumUtil.kt:33]: Caught by failing build on CI, missing 'import com.ionspin.kotlin.crypto.util.isLibsodiumSuccessCode'

File: multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/pwhash/PasswordHash.kt [hunk 2]
```diff
@@ -108,7 +109,7 @@ actual object PasswordHash {
             password,
             password.length.convert()
         )
-        return result == 0
+        return result.isLibSodiumSuccessCode()
```
Comment (ionspin) [inline multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/pwhash/PasswordHash.kt:112]: Also caught by CI, a type here it should be 'isLibsodiumSuccessCode' but the sodium was capitalized

**Review by ionspin — CHANGES_REQUESTED** [review]
Looks good, just a couple of smaller issues to fix and we can get this merged.

File: multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/util/LibsodiumUtil.kt (hunk 1 above)
Comment (ionspin) [reply multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/util/LibsodiumUtil.kt:34]: Oh and also seems to be typo in capitalization `LibSodium` and it should be `Libsodium`

Comment (ReneeVandervelde) [reply multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/util/LibsodiumUtil.kt]: Ah, thanks for catching those typos. I don't have the native targets building properly to test locally yet.

**Comment by ionspin** [comment]
There are some tests that are failing now that we are checking for return value! All failures were in JVM test run.
On mac and windows testKeygen for shorthash failed:
Mac: 
``` 
java.lang.IllegalStateException: Libsodium returned an unexpected return code 1
```
Windows:
```
java.lang.IllegalStateException: Libsodium returned an unexpected return code 16
```
On linux it didn't fail

And on all three OS-es base64 related tests failed:
```
    LibsodiumUtilTest. testToBase64[jvm]
    LibsodiumUtilTest. testToBase64Unaligned[jvm]
```
With various random return codes: 
```
java.lang.IllegalStateException: Libsodium returned an unexpected return code 344999648
```

Looking at the libsodium source code briefly, there is some investigation to be done regarding the `res` parameter and if it's always as expected:
https://github.com/jedisct1/libsodium/blob/f92e5ae836bc12e44336d33de703494b234a1e76/src/libsodium/sodium/codecs.c#L268

But shorthash failure is really curious.

**Comment by ionspin** [comment]
I found the crypto shorthash keygen problem, it's actually a void function but my JNA definition marks it as int:
https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/c9c5f320af22d4e4dc863ca0d02195e313d4249c/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/JnaLibsodiumInterface.kt#L275-L278

**Comment by ionspin** [comment]
The other problem was similar as well, sodium_bin2base64 returns a pointer to the first character of the encoded string, so I was returning contents of that pointer. 

https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/c9c5f320af22d4e4dc863ca0d02195e313d4249c/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/JnaLibsodiumInterface.kt#L155-L165

Since we don't actually use that pointer anywhere (especially in JVM)  I'll just remove the return value and the check.

**Comment by ReneeVandervelde** [comment]
Good catches. Makes sense. 
The pointer functions can be checked for null, if you want error checking.
But if it's not used anywhere, it may not matter.

**Comment by ionspin** [comment]
It's the pointer to the buffer that's supplied to the function to be filled in with the encoded value, and since we are providing the buffer we already have that value.

https://github.com/jedisct1/libsodium/blob/f92e5ae836bc12e44336d33de703494b234a1e76/src/libsodium/sodium/codecs.c#L179-L183

https://github.com/jedisct1/libsodium/blob/f92e5ae836bc12e44336d33de703494b234a1e76/src/libsodium/sodium/codecs.c#L234-L240

It seems just to be a convenience provided by libsodium. 

In any case the test are passing now, thanks for the pull request, and it's awesome that it brought up other improvements, I'll merge it soon and the snapshot will be released as soon as the pipeline is done!

**Review by ionspin — APPROVED** [review]
